/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#001945",
        "secondary-container": "#6292fd",
        "on-secondary-container": "#002b6b",
        "surface-variant": "#e1e3e4",
        "on-background": "#191c1d",
        "surface-container-highest": "#e1e3e4",
        "outline-variant": "#bec9c4",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#005143",
        "primary-container": "#006d5b",
        "on-surface": "#191c1d",
        "primary-fixed-dim": "#81d6c0",
        "on-primary-fixed": "#00201a",
        "on-tertiary-container": "#62f696",
        "tertiary-fixed-dim": "#4ae183",
        "surface-bright": "#f8fafb",
        "on-tertiary-fixed-variant": "#005228",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "surface-tint": "#006b59",
        "on-secondary": "#ffffff",
        "tertiary-container": "#006f38",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#6bfe9c",
        "on-primary-container": "#96ebd5",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#00210c",
        "outline": "#6e7975",
        "primary-fixed": "#9df3dc",
        "secondary": "#1d59c1",
        "inverse-primary": "#81d6c0",
        "surface": "#f8fafb",
        "secondary-fixed-dim": "#b0c6ff",
        "surface-container-low": "#f2f4f5",
        "tertiary": "#005429",
        "inverse-on-surface": "#eff1f2",
        "secondary-fixed": "#d9e2ff",
        "on-secondary-fixed-variant": "#00419c",
        "inverse-surface": "#2e3132",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dadb",
        "on-surface-variant": "#3e4945",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8e9",
        "primary": "#005344",
        "surface-container": "#eceeef",
        "background": "#f8fafb"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"
      },
    },
  },
  plugins: [],
}
